import Head from 'next/head'

export default function Blog() {
  return (
    <div>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>11</div>
    </div>
  )
}
